nodeLinker: node-modules

# Performance optimizations for CI
enableGlobalCache: false
compressionLevel: 0
httpTimeout: 60000

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.7.0.cjs
