version: '3.8'

services:
  api:
    image: ${ECR_REGISTRY}/barum-${ENVIRONMENT}-api:latest
    container_name: barum-api
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "awslogs"
      options:
        awslogs-group: "/aws/ec2/barum-${ENVIRONMENT}"
        awslogs-region: "${AWS_REGION}"
        awslogs-stream: "api"
    networks:
      - barum-network
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

  web-next:
    image: ${ECR_REGISTRY}/barum-${ENVIRONMENT}-web-next:latest
    container_name: barum-web-next
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "awslogs"
      options:
        awslogs-group: "/aws/ec2/barum-${ENVIRONMENT}"
        awslogs-region: "${AWS_REGION}"
        awslogs-stream: "web-next"
    networks:
      - barum-network
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: barum-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - web-next
    restart: unless-stopped
    logging:
      driver: "awslogs"
      options:
        awslogs-group: "/aws/ec2/barum-${ENVIRONMENT}"
        awslogs-region: "${AWS_REGION}"
        awslogs-stream: "nginx"
    networks:
      - barum-network
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
        reservations:
          memory: 128M
          cpus: '0.1'

networks:
  barum-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  barum-data:
    driver: local
  nginx-cache:
    driver: local 